import { test, expect } from '@playwright/test';



test('text visability', async ({ page }) => {
  await page.goto('https://beksar-yernar.web.app/');
  await page.locator('input[type="email"]').click();  
  await page.locator('input[type="email"]').fill('dias.u.tester15@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('Qweasdzxcqw13d#');
  await page.getByRole('button', { name: 'ВХОД' }).click();
  await page.getByRole('button', { name: 'Администрирование' }).click();
  await page.locator('div').filter({ hasText: /^СотрудникиУправление сотрудниками$/ }).first().click();
  await page.getByRole('button', { name: 'Добавить сотрудника' }).click();
  await expect(page.locator('#root')).toContainText('Добавить сотрудника');
  await page.getByRole('button', { name: 'Общие сведения' }).click();
  await expect(page.locator('#root')).toContainText('Общие сведения');
  await expect(page.locator('#root')).toContainText('Роли');
  await expect(page.locator('#root')).toContainText('Имя *Имя *');
  await expect(page.locator('#root')).toContainText('Фамилия *Фамилия *');
  await expect(page.locator('#root')).toContainText('ОтчествоОтчество');
  await expect(page.locator('#root')).toContainText('ИИН *ИИН *');
  await expect(page.locator('#root')).toContainText('Дата рождения *Дата рождения *󰃭');
  await expect(page.locator('#root')).toContainText('Документ, удостоверяющий личность');
  await expect(page.locator('#root')).toContainText('Тип документа *Тип документа *󰅀');
  await expect(page.locator('#root')).toContainText('Дата выдачи *Дата выдачи *󰃭');
  await expect(page.locator('#root')).toContainText('Номер документа *Номер документа *');
  await expect(page.locator('#root')).toContainText('Орган выдачи *Орган выдачи *󰅀');
  await expect(page.locator('#root')).toContainText('Комиссия (%) *Комиссия (%) *');
  await expect(page.locator('#root')).toContainText('Оклад *Оклад *');
  await expect(page.locator('#root')).toContainText('Не начислять процент с продажи *');
  await expect(page.locator('#root')).toContainText('E-mail *E-mail *');
  await expect(page.locator('#root')).toContainText('Пароль *Пароль *');
  await expect(page.locator('#root')).toContainText('Отмена');
  await expect(page.locator('#root')).toContainText('Далее');
  await page.getByRole('button', { name: 'Роли' }).click();
  await expect(page.locator('#root')).toContainText('Роли');
  await expect(page.locator('#root')).toContainText('Выбранные роли');
  await expect(page.locator('#root')).toContainText('Код роли');
  await expect(page.locator('#root')).toContainText('Наименование роли');
  await expect(page.locator('#root')).toContainText('Нет выбранных ролей');
  await expect(page.locator('#root')).toContainText('Добавить роль');
  await expect(page.locator('#root')).toContainText('Назад');
  await expect(page.locator('#root')).toContainText('Сохранить');
});





test('Adding employee', async ({ page }) => {
  await page.goto('https://beksar-yernar.web.app/');
  await page.locator('input[type="email"]').click();   //нужно каждый раз менять здесь цифру
    await page.locator('input[type="email"]').fill('dias.u.tester5@gmail.com');
    await page.locator('input[type="password"]').click();
    await page.locator('input[type="password"]').fill('Qweasdzxcqw13d#');
    await page.getByRole('button', { name: 'ВХОД' }).click();
  await page.getByRole('button', { name: 'Администрирование' }).click();
  await page.locator('div').filter({ hasText: /^СотрудникиУправление сотрудниками$/ }).first().click();
  await page.getByRole('button', { name: 'Добавить сотрудника' }).click();
  await page.locator('.css-11aywtz').first().click();
  await page.locator('.css-11aywtz').first().fill('тестф');
  await page.locator('div:nth-child(3) > div > .css-175oi2r.r-16y2uox > .css-11aywtz').click();
  await page.locator('div:nth-child(3) > div > .css-175oi2r.r-16y2uox > .css-11aywtz').fill('тести');
  await page.locator('div:nth-child(4) > div > .css-175oi2r.r-16y2uox > .css-11aywtz').click();
  await page.locator('div:nth-child(4) > div > .css-175oi2r.r-16y2uox > .css-11aywtz').fill('тесто');
  await page.locator('div').filter({ hasText: /^ИИН \*ИИН \*Дата рождения \*Дата рождения \*󰃭$/ }).getByTestId('text-input-outlined').first().click();
  await page.locator('div').filter({ hasText: /^ИИН \*ИИН \*Дата рождения \*Дата рождения \*󰃭$/ }).getByTestId('text-input-outlined').first().fill('123456789446');
  await page.locator('div').filter({ hasText: /^Дата рождения \*Дата рождения \*󰃭$/ }).nth(1).click();
  await page.getByRole('button', { name: 'typeInDate' }).click();
  await page.getByTestId('text-input-flat').fill('05.06.1999');
  await page.getByTestId('react-native-paper-dates-save').click();
  await page.locator('div').filter({ hasText: /^Должность \*Должность \*󰅀$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Кассир$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Тип документа \*Тип документа \*󰅀$/ }).nth(1).click();
  await page.getByText('Водительское удостоверение').click();
  await page.locator('div:nth-child(8) > div:nth-child(2) > .css-175oi2r.r-1i6wzkk').click();
  await page.getByRole('button', { name: 'июнь' }).click();
  await page.getByRole('button', { name: '1998' }).click();
  await page.getByTestId('react-native-paper-dates-day-1998-5-9').click();
  await page.getByTestId('react-native-paper-dates-save').click();
  await page.locator('div').filter({ hasText: /^Номер документа \*Номер документа \*Орган выдачи \*Орган выдачи \*󰅀$/ }).getByTestId('text-input-outlined').first().click();
  await page.locator('div').filter({ hasText: /^Номер документа \*Номер документа \*Орган выдачи \*Орган выдачи \*󰅀$/ }).getByTestId('text-input-outlined').first().fill('987654321');
  await page.locator('div').filter({ hasText: /^Орган выдачи \*Орган выдачи \*󰅀$/ }).nth(1).click();
  await page.getByText('МЮ РК').click();
  await page.locator('div').filter({ hasText: /^Комиссия \(%\) \*Комиссия \(%\) \*Оклад \*Оклад \*$/ }).getByTestId('text-input-outlined').first().click({ timeout: 10000 });
  await page.locator('div').filter({ hasText: /^Комиссия \(%\) \*Комиссия \(%\) \*Оклад \*Оклад \*$/ }).getByTestId('text-input-outlined').first().fill('30');
  await page.locator('div').filter({ hasText: /^Комиссия \(%\) \*Комиссия \(%\) \*Оклад \*Оклад \*$/ }).getByTestId('text-input-outlined').nth(1).click();
  await page.locator('div').filter({ hasText: /^Комиссия \(%\) \*Комиссия \(%\) \*Оклад \*Оклад \*$/ }).getByTestId('text-input-outlined').nth(1).fill('150000');
  await page.locator('input[type="email"]').click(); //здесь также нужно менять номер
  await page.locator('input[type="email"]').fill('dias.tester615@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('684gg65s4#FFF2');
  await page.screenshot({ fullPage: true });
  await page.getByRole('button', { name: 'Далее' }).click();
  await page.getByRole('button', { name: 'Добавить роль' }).click();
  await page.locator('.css-175oi2r.r-1otgn73.r-1loqt21.r-bnwqim.r-ctqt5z.r-11f147o.r-11g3r6m.r-1qhn6m8').click();
  await page.getByRole('button', { name: 'Сохранить' }).click();
  //проврека на удачное добавленеи
  await expect(page.locator('#root')).toContainText('тестф тести тесто', { timeout: 10000 });
  await expect(page.locator('#root')).toContainText('123456789446', { timeout: 10000 });
  await page.screenshot({ fullPage: true });
});


test('is clickable', async ({ page }) => {
    await page.goto('https://beksar-yernar.web.app/');
    await page.locator('input[type="email"]').click();  
    await page.locator('input[type="email"]').fill('dias.u.tester5@gmail.com');
    await page.locator('input[type="password"]').click();
    await page.locator('input[type="password"]').fill('Qweasdzxcqw13d#');
    await page.getByRole('button', { name: 'ВХОД' }).click();
    await page.getByRole('button', { name: 'Администрирование' }).click();
    await page.locator('div').filter({ hasText: /^СотрудникиУправление сотрудниками$/ }).first().click();
    await page.getByRole('button', { name: 'Добавить сотрудника' }).click();
    await page.getByRole('button', { name: 'Общие сведения' }).click();
    await page.getByRole('button', { name: 'Роли' }).click();
    await page.getByRole('button', { name: 'Общие сведения' }).click();
    await page.locator('.css-11aywtz').first().click();
    await page.locator('div:nth-child(3) > div > .css-175oi2r.r-16y2uox > .css-11aywtz').click();
    await page.locator('div:nth-child(4) > div > .css-175oi2r.r-16y2uox > .css-11aywtz').click();
    await page.locator('div').filter({ hasText: /^ИИН \*ИИН \*Дата рождения \*Дата рождения \*󰃭$/ }).getByTestId('text-input-outlined').first().click();
    await page.locator('div').filter({ hasText: /^Должность \*Должность \*󰅀$/ }).nth(1).click();
    await page.getByText('Менеджер').click();
    await page.locator('div').filter({ hasText: /^Должность \*Должность \*󰅀$/ }).nth(1).click();
    await page.getByText('Продавец-консультант').click();
    await page.locator('div').filter({ hasText: /^Должность \*Должность \*󰅀$/ }).nth(1).click();
    await page.locator('div').filter({ hasText: /^Администратор$/ }).nth(1).click();
    await page.getByTestId('right-icon-adornment').nth(1).click();
    await page.locator('div').filter({ hasText: /^Должность \*Должность \*󰅀$/ }).nth(1).click();
    await page.locator('div').filter({ hasText: /^Кассир$/ }).nth(1).click();
    await page.locator('div').filter({ hasText: /^ИИН \*ИИН \*Дата рождения \*Дата рождения \*󰃭$/ }).getByTestId('right-icon-adornment').click();
    await page.locator('div').filter({ hasText: /^Дата рождения \*Дата рождения \*󰃭$/ }).nth(1).click();
    await page.getByRole('button', { name: 'июнь' }).click();
    await page.getByRole('button', { name: 'next' }).click();
    await page.getByRole('button', { name: 'previous' }).click();
    await page.getByText('selectSingle 󰲶').click();
    await page.getByRole('button', { name: 'typeInDate' }).click();
    await page.getByTestId('text-input-flat').click();
    await page.getByTestId('react-native-paper-dates-close').click();
    await page.locator('div').filter({ hasText: /^Тип документа \*Тип документа \*󰅀$/ }).nth(1).click();
    await page.getByText('Паспорт').click();
    await page.getByTestId('right-icon-adornment').nth(2).click();
    await page.locator('div').filter({ hasText: /^Тип документа \*Тип документа \*󰅀$/ }).nth(1).click();
    await page.locator('div').filter({ hasText: /^Удостоверение личности$/ }).nth(1).click();
    await page.getByTestId('right-icon-adornment').nth(2).click();
    await page.locator('div').filter({ hasText: /^Тип документа \*Тип документа \*󰅀$/ }).nth(1).click();
    await page.locator('div').filter({ hasText: /^Водительское удостоверение$/ }).nth(1).click();
    await page.locator('div:nth-child(8) > div:nth-child(2) > .css-175oi2r.r-1i6wzkk').click();
    await page.getByRole('button', { name: 'previous' }).click();
    await page.getByRole('button', { name: 'next' }).click();
    await page.getByTestId('react-native-paper-dates-day-2025-5-17').click();
    await page.getByTestId('react-native-paper-dates-day-2025-5-11').click();
    await page.getByTestId('react-native-paper-dates-day-2025-5-10').click();
    await page.getByRole('button', { name: 'typeInDate' }).click();
    await page.getByTestId('react-native-paper-dates-save').click();
    await page.locator('div').filter({ hasText: /^Номер документа \*Номер документа \*Орган выдачи \*Орган выдачи \*󰅀$/ }).getByTestId('text-input-outlined').first().click();
    await page.locator('div').filter({ hasText: /^Орган выдачи \*Орган выдачи \*󰅀$/ }).nth(1).click();
    await page.getByText('МВД РК').click();
    await page.locator('div').filter({ hasText: /^Орган выдачи \*Орган выдачи \*󰅀$/ }).nth(1).click();
    await page.getByText('МЮ РК').click();
    await page.locator('div').filter({ hasText: /^Номер документа \*Номер документа \*Орган выдачи \*Орган выдачи \*󰅀$/ }).getByTestId('right-icon-adornment').click();
    await page.locator('div').filter({ hasText: /^Комиссия \(%\) \*Комиссия \(%\) \*Оклад \*Оклад \*$/ }).getByTestId('text-input-outlined').first().click();
    await page.locator('div').filter({ hasText: /^Комиссия \(%\) \*Комиссия \(%\) \*Оклад \*Оклад \*$/ }).getByTestId('text-input-outlined').nth(1).click();
    await page.getByText('Не начислять процент с продажи *').click();
    await page.getByText('Не начислять процент с продажи *').click();
    await page.getByRole('checkbox').click();
    await page.locator('input[type="email"]').click();
    await page.locator('input[type="password"]').click();
    await page.getByRole('button', { name: 'Далее' }).click();
    await page.locator('.css-175oi2r.r-gjda0u').click();
    await page.getByRole('button', { name: 'Назад' }).click();
    await page.getByRole('button', { name: 'Отмена' }).click();
    await page.getByRole('button', { name: 'Добавить сотрудника' }).click();
    await page.getByRole('button', { name: 'Роли' }).click();
    await page.getByText('Общие сведенияРолиВыбранные ролиКод ролиНаименование ролиНет выбранных ролей󰐕До').click();
    await page.getByRole('button', { name: 'Добавить роль' }).click();
    await page.locator('.css-175oi2r.r-1otgn73.r-1loqt21.r-bnwqim.r-ctqt5z.r-11f147o.r-11g3r6m.r-1qhn6m8').click();
    await page.getByRole('button', { name: 'Добавить роль' }).click();
    await page.locator('.css-175oi2r.r-1otgn73.r-1loqt21.r-bnwqim.r-ctqt5z.r-11f147o.r-11g3r6m.r-1qhn6m8').click();
    await page.getByRole('button', { name: 'Добавить роль' }).click();
    await page.locator('.css-175oi2r.r-1otgn73.r-1loqt21.r-bnwqim.r-ctqt5z.r-11f147o.r-11g3r6m.r-1qhn6m8').click();
    await page.getByRole('button', { name: 'Назад' }).click();
    await page.getByRole('button', { name: 'Роли' }).click();
    await page.getByRole('button', { name: 'Сохранить' }).click();
    await page.getByRole('button').filter({ hasText: '󰅖' }).click();
    await page.getByTestId('icon-button').click();
    await page.getByRole('button', { name: 'Close menu' }).click();
    await page.getByText('тестф тести тесто').click();
    await page.getByRole('button', { name: 'Роли' }).click();
    await page.getByRole('button', { name: 'Общие сведения' }).click();
    await page.locator('div').filter({ hasText: /^󰅁$/ }).nth(2).click();
  });